apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: devops-knowledge-share-ui-svelte
profiles:
- name: docker-desktop
  activation:
    - kubeContext: docker-desktop
  build:
    artifacts:
    - image: devops-knowledge-share-ui-svelte
  deploy:
    helm:
      releases:
      - name: devops-knowledge-share-ui-svelte
        namespace: default
        chartPath: ./charts/devops-knowledge-share-ui-svelte
        artifactOverrides:
          image: devops-knowledge-share-ui-svelte
  portForward:
  - resourceType: Service
    resourceName: devops-knowledge-share-ui-svelte
    namespace: default
    port: 3000
    localPort: 3000
