version: 2.1
description: |
  Build a Svelte application.

orbs:
  custom-orb: liatrio-poc/circleci-orb-poc@dev:jeff-playground
  
workflows:
  svelte-application:
    jobs:
      - custom-orb/npm-build:
          executor: custom-orb/default
      - deploy:
          name: deploy-job
      - custom-orb/run-metrics:
          requires:
            - deploy-job
          context:
            - metrics
jobs:
  deploy:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run:
          name: "echo message"
          command: |
            echo 'hello world'
