version: 2.1
description: |
  Build a Svelte application.

orbs:
  custom-orb: liatrio-poc/circleci-orb-poc@dev:jeff-playground
  
workflows:
  svelte-application:
    jobs:
      - custom-orb/npm-build:
          executor: custom-orb/default
      #- kickoff-metrics:
      #    context: 
      #      - metrics
#jobs:
#  kickoff-metrics:
#    docker:
#      - image: 'cimg/node:lts'
#    steps:
#      - checkout
#      - run:
#          name: "echo environment variables from org-global context"
#          when: always
#          command: |
#            PROJECT_SLUG=gh/liatrio/circleci-metrics
#
#            curl --request POST \
#                 --url https://circleci.com/api/v2/project/$PROJECT_SLUG/pipeline \
#                 --header "authorization: Basic $API_TOKEN" \
#                 --data '{"branch":"main"}'
#                 #--data '{"branch":"main","parameters":{"deploy_prod":true}}'
