apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      {{- if not (eq .Values.tag "") -}}
      - image: {{ .Values.image }}:{{ .Values.tag }}
      {{ else }}
      - image: {{ .Values.image }}
      {{- end }}
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}