apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: app
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
